version: '2'
services:
  elasticsearch:
    image: daocloud.io/genius0215/elasticsearch
    container_name: elasticsearch
    volumes:
    - esdata:/usr/share/elasticsearch/data
    - /root/app/docker-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: '123456'
    networks:
      elk:
        ipv4_address: 172.25.0.2
    

  logstash:
    image: daocloud.io/genius0215/logstash
    container_name: logstash
    volumes:
    - /root/app/docker-elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    - /root/app/docker-elk/logstash/config/pipeline.yml:/usr/share/logstash/config/pipeline.yml:ro
    - /root/app/docker-elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
    - /var/log:/hostlog:ro
    ports:
    - 5000:5000
    environment:
      LS_JAVA_OPTS: -Xmx256m -Xms256m
    user: root
    networks:
      elk:
        ipv4_address: 172.25.0.3
    depends_on:
    - elasticsearch
    restart: always

  kibana:
    image: daocloud.io/genius0215/kibana
    container_name: kibana
    volumes:
    - /root/app/docker-elk/kibana/config/:/usr/share/kibana/config:ro
    ports:
    - 5601:5601
    networks:
      elk:
        ipv4_address: 172.25.0.4
    depends_on:
    - elasticsearch
    restart: always

  metricbeat:
    image: daocloud.io/genius0215/metricbeat
    container_name: metricbeat
    volumes:
    - /root/app/docker-elk/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
    - /root/app/docker-elk/metricbeat/modules.d:/usr/share/metricbeat/modules.d:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc:/hostfs/proc:ro
    - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
    - /:/hostfs:ro
    user: root
    network_mode: host
    depends_on:
    - elasticsearch
    - kibana
    - logstash
    command: -system.hostfs=/hostfs -e
    restart: always

  nginx:
    image: daocloud.io/genius0215/nginx
    container_name: nginx
    volumes:
    - /root/app/docker-elk/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - /root/app/docker-elk/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
    - 80:80
    - 443:443
    network_mode: host
    depends_on:
    - kibana
    restart: always

volumes:
  esdata:
    driver: local

networks:
  elk:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/16
