FROM docker.elastic.co/elasticsearch/elasticsearch-platinum:7.6.2

LABEL maintainer="genius840215@163.com"

COPY ./config/elasticsearch.yml /usr/share/elasticsearch/conifg/elasticsearch.yml

RUN echo "Asia/Shanghai" > /etc/timezone
