# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: var.log.system
  path.config: "/usr/share/logstash/pipeline/var.log.system.conf"
- pipeline.id: mysql.slow
  path.config: "/usr/share/logstash/pipeline/mysql.slow.conf"